### ISSUE TITLE
createVariable chokes on scalar datasets

### ISSUE THREAD

**Issue by mraspaud** [shoyer/h5netcdf#12]
With the legacy API, the following crashes (while it works with netCDF4):

```python
import h5netcdf.legacyapi as netCDF4
with netCDF4.Dataset('mydata.nc', 'w') as ds:
    v = ds.createVariable('myvar', int, (), zlib=6, fill_value=None)
```

here is the traceback:
```
Traceback (most recent call last):
  File "test_h5nc.py", line 31, in <module>
    v = ds.createVariable('myvar', int, (), zlib=6, fill_value=None)
  File "/home/a001673/usr/src/h5netcdf/h5netcdf/legacyapi.py", line 68, in createVariable
    chunks=chunksizes, fillvalue=fill_value, **kwds)
  File "/home/a001673/usr/src/h5netcdf/h5netcdf/core.py", line 262, in create_variable
    fillvalue, **kwargs)
  File "/home/a001673/usr/src/h5netcdf/h5netcdf/core.py", line 244, in _create_child_variable
    **kwargs)
  File "/home/a001673/usr/src/h5py/h5py/_hl/group.py", line 103, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/a001673/usr/src/h5py/h5py/_hl/dataset.py", line 107, in make_new_dset
    shuffle, fletcher32, maxshape, scaleoffset)
  File "/home/a001673/usr/src/h5py/h5py/_hl/filters.py", line 87, in generate_dcpl
    raise TypeError("Scalar datasets don't support chunk/filter options")
TypeError: Scalar datasets don't support chunk/filter options
```

**Comment by mraspaud** [comment]
fixed with #13
