### ISSUE TITLE
Error importing compound type

### ISSUE THREAD

**Issue by trevor** [shoyer/h5netcdf#49]
```
import h5netcdf
import netCDF4
import numpy as np
ncfile = netCDF4.Dataset('test.nc','w',format='NETCDF4')
complex128 = np.dtype([('real',np.float64),('imag',np.float64)])
complex128_t = ncfile.createCompoundType(complex128,'complex128')
ncfile.close()
h5netcdf.File('test.nc', 'r')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 683, in __repr__
    return '\n'.join([header] + self._repr_body())
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 538, in _repr_body
    ['Attributes:'] +
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 537, in <listcomp>
    for k, v in self.variables.items()] +
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 112, in dimensions
    self._dimensions = self._lookup_dimensions()
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 96, in _lookup_dimensions
    for axis, dim in enumerate(self._h5ds.dims):
AttributeError: 'Datatype' object has no attribute 'dims'
```

```
% h5dump test.nc
HDF5 "test.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 57;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.2"
      }
   }
   DATATYPE "complex128" H5T_COMPOUND {
      H5T_IEEE_F64LE "real";
      H5T_IEEE_F64LE "imag";
   }
}
}
```

**Comment by shoyer** [comment]
Hmm. It appears that h5netcdf tries to read the `Datatype` object as an HDF5 Dataset.

I suspect the right place to fix this is to add another check to these lines, to verify that the object we're adding to `self._variables` is a `h5py.Dataset`:
https://github.com/shoyer/h5netcdf/blob/f15ffdcab090aca20c2f323abbe5a0dbac6f5947/h5netcdf/core.py#L263-L267

Contributions would be welcome!
