### ISSUE TITLE
AttributeError when opening file with only groups at root level

### ISSUE THREAD

**Issue by gerritholl** [shoyer/h5netcdf#63]
When I open the this file with no other arguments, h5netcdf raises an AttributeError:

Data available from EUMETSAT: https://www.eumetsat.int/website/home/Satellites/FutureSatellites/MeteosatThirdGeneration/MTGData/MTGUserTestData/index.html  --> ftp://ftp.eumetsat.int/pub/OPS/out/test-data/Test-data-for-External-Users/MTG_FCI_Test-Data/ --> uncompressed

```
import h5netcdf
f = "/path/to/file/W_XX...0067.nc"
ds = h5netcdf.File(f, 'r')
```

results in an `AttributeError` as follows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 719, in __repr__
    return '\n'.join([header] + self._repr_body())
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 541, in _repr_body
    ['Attributes:'] +
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 540, in <listcomp>
    for k, v in self.variables.items()] +
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 114, in dimensions
    self._dimensions = self._lookup_dimensions()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 98, in _lookup_dimensions
    for axis, dim in enumerate(self._h5ds.dims):
AttributeError: 'Datatype' object has no attribute 'dims'
```

Strangely, when run on the commandline I get:

```
Exception ignored in: <function File.close at 0x7f1acf790598>
Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 701, in close
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5py/_hl/files.py", line 431, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 267, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by shoyer** [comment]
My suspicion is that this simply isn’t a valid netcdf file, because some dimensions are not set. See https://github.com/shoyer/h5netcdf/issues/43 for discussion about adding this as a feature.

**Comment by kmuehlbauer** [comment]
@gerritholl @shoyer I've tracked that down to some variables.

```
boolean <class 'h5py._hl.datatype.Datatype'>
trilean <class 'h5py._hl.datatype.Datatype'>
auxiliary_dataset_status_type <class 'h5py._hl.datatype.Datatype'>
ssd_type <class 'h5py._hl.datatype.Datatype'>
swath_direction_type <class 'h5py._hl.datatype.Datatype'>
manoeuvre_type <class 'h5py._hl.datatype.Datatype'>
reference_frame_type <class 'h5py._hl.datatype.Datatype'>
yaw_flip_type <class 'h5py._hl.datatype.Datatype'>
fci_mode_type <class 'h5py._hl.datatype.Datatype'>
resampling_method_type <class 'h5py._hl.datatype.Datatype'>
weighting_function_type <class 'h5py._hl.datatype.Datatype'>
projection_type <class 'h5py._hl.datatype.Datatype'>
```
If I read them with a prepared version of #64, I get
`print(ds['trilean']._h5ds)`
`<HDF5 named type "trilean" (dtype |u1)>`

This named type doesn't have a dimension-object:
`dir(ds['trilean']._h5ds)`
```
['__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_d',
 '_e',
 '_id',
 '_lapl',
 '_lcpl',
 'attrs',
 'dtype',
 'file',
 'id',
 'name',
 'parent',
 'ref',
 'regionref']
```

**Comment by kmuehlbauer** [comment]
FYI: netcdf-c interprets the offending *variables* as `types`.

```
netcdf W_XX-EUMETSAT-Darmstadt\,IMG+SAT\,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY--L2P-NC4E_C_EUMT_20170410021444_GTT_DEV_20170410021000_20170410021008_N_JLS_C_0014_0001 {
types:
  ubyte enum boolean {false = 0, true = 1} ;
  ubyte enum trilean {false = 0, true = 1, undefined = 2} ;
  ubyte enum auxiliary_dataset_status_type {OK = 0, out_of_validity_time = 1, 
      not_available = 2} ;
  ubyte enum ssd_type {\0.5km = 0, \1km = 1, \2km = 2} ;
  ubyte enum swath_direction_type {forward_scan = 0, retrace = 1} ;
dimensions:
        auxiliary_dataset = 1 ;
        index = 858 ;
        number_of_l0_channels = 17 ;
        number_of_l1c_channels = 16 ;
        number_of_reference_grids = 2 ;
        offset_size_dim1 = 10000 ;
        offset_size_dim2 = 1900 ;
variables:
        string auxiliary_dataset_identifier(auxiliary_dataset) ;
        auxiliary_dataset_status_type auxiliary_dataset_status(auxiliary_dataset) ;
        ushort index(index) ;
                index:long_name = "Coordinate variable of indices drived from repeat cycle data vectors" ;
        ushort index_offset ;
                index_offset:long_name = "Offset index for data vectors" ;
        double time(index) ;
                time:title = "UTC Time  for geometric data vectors" ;
                time:long_name = "UTC  time at which the geometric metadata are calculated." ;
                time:standard_name = "time" ;
                time:units = "seconds since 2000-01-01 00:00:00.0" ;
        string l1c_channels_present(number_of_l1c_channels) ;
                string l1c_channels_present:long_name = "“Level 1c spectral channels present in dataset”" ;
        ubyte offset_size_var(offset_size_dim1, offset_size_dim2) ;

// global attributes:
                :Conventions = "CF-1.7" ;
                :title = "FCI Level 1C Rectified Radiance Product" ;
                :summary = "<configured_value>" ;
                :keywords = "<configured_value>" ;
                :keywords_vocabulary = "<configured_value>" ;
                :history = "Orignal generated version" ;
                :institution = "EUMETSAT" ;
                :product_id = "FCI1CRRADFDHSI" ;
                :baseline_version = "n.x.y" ;
                :release_version = "original" ;
                :processor_version = "<configured_value>" ;
                :algorithm_version = "<configured_value>" ;
                :source = "IDPFI" ;
                :runtime_data = "default_value should be given here" ;
                :parent_data = "<runtime_value>" ;
                :linked_data = "<runtime_value>" ;
                string :references = "“www.eumetsat.int”  " ;
                :comment = "DUPLICATED ABOVE!!" ;
                :group_tag = "MTI1_FCI_1C_RRAD_FDHSI_YYY_DDD_NNNN_original" ;
                :processed_count_in_repeat_cycle = "<runtime_value>" ;
                :instrument_configuration_id = "<runtime_value>" ;
                :instrument_configuration_id_version = "<runtime_value>" ;
                :subsettable_groups = "/data/measured/.." ;
                :subsettable_groups_present = "/data/measured/.." ;
                :mtg_name = "<runtime_value>" ;
                :id = "<configured_value>" ;
                :naming_authority = "<configured_value>" ;
                :creator_type = "institution" ;
                :creator_institution = "EUMETSAT" ;
                :creator_url = "null" ;
                :license = "null" ;
                :standard_name_vocabulary = "CF Standard Name Table v27" ;
                :project = "MTG" ;
                :time_coverage_duration = "null" ;
                :time_coverage_resolution = "null" ;
                :cdm_datatype = "null" ;
                :date_time_position = "hh:mm:ss" ;
                :time_position = "YYYYMMDD hh:mm:ss" ;
                :geospatial_lat_min = 9.96920996838687e+36 ;
                :geospatial_lat_max = 9.96920996838687e+36 ;
                :geospatial_lon_min = 9.96920996838687e+36 ;
                :geospatial_lon_max = 9.96920996838687e+36 ;
                :format_version = "IDPFIV2_1.0" ;
                :creator_name = "Mounir Lekouara" ;
                :creator_email = "mounir.lekouara@eumetsat.int" ;
                :location_indicator = "XX_EUMETSAT_Darmstadt" ;
                :data_designator = "IMG+SAT" ;
                :platform = "MTI1" ;
                :data_source = "FCI" ;
                :processing_level = "1C" ;
                :coverage = "FD" ;
                :type = "RRAD" ;
                :subtype = "FDHSI" ;
                :component1 = "CHK" ;
                :component2 = "BODY" ;
                :time_coverage_start = "20170410021000" ;
                :time_coverage_end = "20170410021008" ;
                :processing_mode = "N" ;
                :disposition_mode = "C" ;
                :facility_or_tool = "GTT" ;
                :environment = "DEV" ;
                :date_created = "20170410021508" ;
                :repeat_cycle_in_day = "0014" ;
                :count_in_repeat_cycle = "0001" ;
                :purpose = "L2P" ;
                :format = "NC4E" ;
                :component3 = "null" ;
                :special_compression = "null" ;
                :subsetting = "null" ;
                :alternative_name = "null" ;

```
netCDF4 is obviously omitting everything:

```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.7
    title: FCI Level 1C Rectified Radiance Product
    summary: <configured_value>
    keywords: <configured_value>
    keywords_vocabulary: <configured_value>
    history: Orignal generated version
    institution: EUMETSAT
    product_id: FCI1CRRADFDHSI
    baseline_version: n.x.y
    release_version: original
    processor_version: <configured_value>
    algorithm_version: <configured_value>
    source: IDPFI
    runtime_data: default_value should be given here
    parent_data: <runtime_value>
    linked_data: <runtime_value>
    references: “www.eumetsat.int”  
    comment: DUPLICATED ABOVE!!
    group_tag: MTI1_FCI_1C_RRAD_FDHSI_YYY_DDD_NNNN_original
    processed_count_in_repeat_cycle: <runtime_value>
    instrument_configuration_id: <runtime_value>
    instrument_configuration_id_version: <runtime_value>
    subsettable_groups: /data/measured/..
    subsettable_groups_present: /data/measured/..
    mtg_name: <runtime_value>
    id: <configured_value>
    naming_authority: <configured_value>
    creator_type: institution
    creator_institution: EUMETSAT
    creator_url: null
    license: null
    standard_name_vocabulary: CF Standard Name Table v27
    project: MTG
    time_coverage_duration: null
    time_coverage_resolution: null
    cdm_datatype: null
    date_time_position: hh:mm:ss
    time_position: YYYYMMDD hh:mm:ss
    geospatial_lat_min: 9.969209968386869e+36
    geospatial_lat_max: 9.969209968386869e+36
    geospatial_lon_min: 9.969209968386869e+36
    geospatial_lon_max: 9.969209968386869e+36
    format_version: IDPFIV2_1.0
    creator_name: Mounir Lekouara
    creator_email: mounir.lekouara@eumetsat.int
    location_indicator: XX_EUMETSAT_Darmstadt
    data_designator: IMG+SAT
    platform: MTI1
    data_source: FCI
    processing_level: 1C
    coverage: FD
    type: RRAD
    subtype: FDHSI
    component1: CHK
    component2: BODY
    time_coverage_start: 20170410021000
    time_coverage_end: 20170410021008
    processing_mode: N
    disposition_mode: C
    facility_or_tool: GTT
    environment: DEV
    date_created: 20170410021508
    repeat_cycle_in_day: 0014
    count_in_repeat_cycle: 0001
    purpose: L2P
    format: NC4E
    component3: null
    special_compression: null
    subsetting: null
    alternative_name: null
    dimensions(sizes): auxiliary_dataset(1), index(858), number_of_l0_channels(17), number_of_l1c_channels(16), number_of_reference_grids(2), offset_size_dim1(10000), offset_size_dim2(1900)
    variables(dimensions): <class 'str'> auxiliary_dataset_identifier(auxiliary_dataset), uint8 auxiliary_dataset_status(auxiliary_dataset), uint16 index(index), uint16 index_offset(), float64 time(index), <class 'str'> l1c_channels_present(number_of_l1c_channels), uint8 offset_size_var(offset_size_dim1,offset_size_dim2)
    groups: state, data
```

**Comment by kmuehlbauer** [comment]
seems this is related #49
